name: current_location
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  google_sign_in: ^5.4.1
  cloud_firestore: ^3.4.6
  date_time_format: ^2.0.1
  google_fonts: ^3.0.1
  flutter_signin_button: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  google_maps_flutter: ^2.2.0
  geolocator: ^9.0.1
  flutter_google_places: ^0.3.0
  location: ^4.4.0
  permission_handler: ^10.0.0
  flutter_image_map: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

#  assets:
#    - assets/images/
